/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeUI;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.WindowConstants;
import javax.swing.*;
 /* @author Fawk
 */
public class EmployeeUI extends javax.swing.JFrame {

    public HashTable hTable = new HashTable(5);
    public String dataBase;
    protected String fName;
    protected String mName;
    protected String lName;
    protected int eN;
    protected String gender;
    protected double dRate;
    protected double nIncome;
    protected double hourlyWage;
    protected float hrsPerWeek;
    protected int weeksPerYear;
    protected double yearlySalary;
    EmployeeInfo tempEmployee;
    PartTime tempPT;
    FullTime tempFT;
    /**
     * Creates new form EmployeeUI
     */
    public EmployeeUI() {
        initComponents();
        try {
            // Open the hash table from the database file.
            hTable.open("C:/Documents/DB.txt");
        } catch (FileNotFoundException ex) {
            outputField.setText("\n !!!!The default database cannot be found!!!!.\n Please select the database (DB.txt) file" + "\n before Continuing.");

        } catch (IOException ex) {
            Logger.getLogger(EmployeeUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dbChooserFrame = new javax.swing.JFrame();
        dbChooser = new javax.swing.JFileChooser();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        genderBox = new javax.swing.JComboBox();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        ptRadio = new javax.swing.JRadioButton();
        ftRadio = new javax.swing.JRadioButton();
        occupationTypeLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        deductionRateLabel = new javax.swing.JLabel();
        deductionRateField = new javax.swing.JTextField();
        yearlySalaryField = new javax.swing.JTextField();
        hrsPerWeekLabel = new javax.swing.JLabel();
        hrlyWageLabel = new javax.swing.JLabel();
        hrsPerYearLabel = new javax.swing.JLabel();
        hourlyWageField = new javax.swing.JTextField();
        hrsPerWeekField = new javax.swing.JTextField();
        weeksPerYearField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        displayButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        netIncomeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Calculate = new javax.swing.JButton();
        employeeNumberField = new javax.swing.JTextField();
        employeeNumberLabel = new javax.swing.JLabel();
        middleNameLabel1 = new javax.swing.JLabel();
        middleNameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputField = new javax.swing.JTextArea();
        searchButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openFile = new javax.swing.JMenuItem();
        saveFile = new javax.swing.JMenuItem();

        dbChooserFrame.setTitle("Database Chooser");
        dbChooserFrame.setMinimumSize(new java.awt.Dimension(500, 400));
        dbChooserFrame.setResizable(false);

        dbChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dbChooserFrameLayout = new javax.swing.GroupLayout(dbChooserFrame.getContentPane());
        dbChooserFrame.getContentPane().setLayout(dbChooserFrameLayout);
        dbChooserFrameLayout.setHorizontalGroup(
            dbChooserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
            .addGroup(dbChooserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dbChooserFrameLayout.createSequentialGroup()
                    .addGap(0, 26, Short.MAX_VALUE)
                    .addComponent(dbChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 26, Short.MAX_VALUE)))
        );
        dbChooserFrameLayout.setVerticalGroup(
            dbChooserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(dbChooserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dbChooserFrameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(dbChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Database");
        setBackground(new java.awt.Color(0, 255, 255));

        firstNameLabel.setText("First Name:");

        lastNameLabel.setText("Last Name:");

        sexLabel.setText("Sex:");

        genderBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        genderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderBoxActionPerformed(evt);
            }
        });

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });

        addButton.setText("Add Employee");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(ptRadio);
        ptRadio.setText("Part Time");
        ptRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(ftRadio);
        ftRadio.setText("Full Time");
        ftRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftRadioActionPerformed(evt);
            }
        });

        occupationTypeLabel.setText("Occupation Type:");

        deleteButton.setText("Delete Employee");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        deductionRateLabel.setText("Deduction Rate (%) :");

        deductionRateField.setText("0");

        yearlySalaryField.setText("0");

        hrsPerWeekLabel.setText("Hours Per Week:");

        hrlyWageLabel.setText("Hourly Wage:");

        hrsPerYearLabel.setText("Weeks Per Year:");

        hourlyWageField.setText("0");
        hourlyWageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyWageFieldActionPerformed(evt);
            }
        });

        hrsPerWeekField.setText("0");

        weeksPerYearField.setText("0");
        weeksPerYearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeksPerYearFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Yearly Salary:");

        jLabel2.setText("Search:");

        searchField.setText("0");
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        displayButton.setText("Display");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        modifyButton.setText("Modify");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        netIncomeField.setEditable(false);

        jLabel3.setText("Net Income:");

        Calculate.setText("Calculate");
        Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateActionPerformed(evt);
            }
        });

        employeeNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNumberFieldActionPerformed(evt);
            }
        });

        employeeNumberLabel.setText("Employee Number:");

        middleNameLabel1.setText("Middle Name:");

        middleNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNameFieldActionPerformed(evt);
            }
        });

        outputField.setEditable(false);
        outputField.setColumns(20);
        outputField.setRows(5);
        jScrollPane1.setViewportView(outputField);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        openFile.setText("Open File");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });
        jMenu1.add(openFile);

        saveFile.setText("Save File");
        saveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileActionPerformed(evt);
            }
        });
        jMenu1.add(saveFile);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(occupationTypeLabel)
                            .addComponent(sexLabel)
                            .addComponent(deductionRateLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(employeeNumberLabel)
                            .addComponent(middleNameLabel1)
                            .addComponent(firstNameLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(hrlyWageLabel)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hrsPerYearLabel)
                                    .addComponent(hrsPerWeekLabel)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(employeeNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(deductionRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(hourlyWageField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(weeksPerYearField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ftRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ptRadio))
                            .addComponent(middleNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(firstNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(yearlySalaryField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(hrsPerWeekField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(Calculate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(netIncomeField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton)
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(displayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(searchField)
                                .addComponent(searchButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(middleNameLabel1)
                            .addComponent(middleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(employeeNumberLabel)
                            .addComponent(employeeNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deductionRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deductionRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexLabel)
                            .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(occupationTypeLabel)
                            .addComponent(ftRadio)
                            .addComponent(ptRadio))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(yearlySalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hrlyWageLabel)
                            .addComponent(hourlyWageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hrsPerWeekLabel)
                            .addComponent(hrsPerWeekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hrsPerYearLabel)
                            .addComponent(weeksPerYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(netIncomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Calculate)))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton)
                            .addComponent(deleteButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(displayButton)
                            .addComponent(modifyButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderBoxActionPerformed

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        dbChooserFrame.setVisible (true);
        dbChooser.setVisible(true);
        
    }//GEN-LAST:event_openFileActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        
        
        fName = firstNameField.getText();
        mName = middleNameField.getText();
        lName = lastNameField.getText();
        eN = Integer.parseInt(employeeNumberField.getText());
        
       EmployeeInfo result = hTable.search(eN);
       if (result == null){
                
        dRate = Double.parseDouble(deductionRateField.getText());
        gender = (String)genderBox.getSelectedItem( );
       
         if (ftRadio.isSelected()) {
         
             {
             yearlySalary = Double.parseDouble(yearlySalaryField.getText());  
             }
             nIncome = yearlySalary * (1 - (dRate / 100));
             FullTime employee = new FullTime(eN, fName, mName, lName, gender, dRate, yearlySalary, nIncome);
             
             hTable.add(employee);
        
        } 
         else {
            if (ptRadio.isSelected()) {
                
            hourlyWage = Double.parseDouble (hourlyWageField.getText());
            hrsPerWeek = Float.parseFloat (hrsPerWeekField.getText());
            weeksPerYear = Integer.parseInt (weeksPerYearField.getText());        
            nIncome = (hourlyWage * hrsPerWeek * weeksPerYear) * (1 - (dRate / 100));
            PartTime employee = new PartTime(eN, fName, mName, lName, gender, dRate, hourlyWage, hrsPerWeek, weeksPerYear, nIncome);
            hTable.add(employee);

            }
         }
         firstNameField.setText("");
         middleNameField.setText("");
         lastNameField.setText("");
         employeeNumberField.setText("");
         deductionRateField.setText("0");
         ftRadio.setSelected(false);
         ptRadio.setSelected(false);
         yearlySalaryField.setText("0");
         hourlyWageField.setText("0");
         hrsPerWeekField.setText("0");
         weeksPerYearField.setText("0");
         netIncomeField.setText("");
       }
       else{
           outputField.setText("An employee with that employee number already exists. \n Please enter a new number.");
          
                   
       }
    }//GEN-LAST:event_addButtonActionPerformed
                                  
    private void ftRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftRadioActionPerformed

        yearlySalaryField.setEnabled (true);
        hourlyWageField.setEnabled (false);
        hrsPerWeekField.setEnabled (false);
        weeksPerYearField.setEnabled (false);
        
    }//GEN-LAST:event_ftRadioActionPerformed
    

    private void weeksPerYearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeksPerYearFieldActionPerformed

    }//GEN-LAST:event_weeksPerYearFieldActionPerformed

    private void hourlyWageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyWageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourlyWageFieldActionPerformed

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        
        outputField.append("\n \n Employee List: \n");
        int tempInt = 0;
        for (int s = 0; s < hTable.k; s++) {
            
            int size = hTable.buckets[s].size();
           
                for (int g = 0; g < size; g++) {
                  if (hTable.buckets[s].get(g) instanceof PartTime){      
                    tempInt++;
                    tempPT = (PartTime) hTable.buckets[s].get(g);
                    outputField.append("\n\n" +tempInt +". " + tempPT.lastName + ", " + tempPT.middleName + " " + tempPT.firstName +"(Part Time)" + "\nEmployee Number: "+ tempPT.employeeNumber + "\nGender: " + tempPT.gender +"\nDeduction Rate:" +tempPT.deductionRate+"\nHourly Wage:" +tempPT.hourlyWage+"\nHours Per Week:" +tempPT.hrsPerWeek+"\nWeeks Per Year:" +tempPT.weeksPerYear+ "\nNet Income:" + tempPT.netIncome);                    
                  }
                  if (hTable.buckets[s].get(g) instanceof FullTime ){
                     tempInt++;
                     tempFT = (FullTime) hTable.buckets[s].get(g);
                    outputField.append("\n\n" +tempInt +". " + tempFT.lastName + ", " + tempFT.middleName + " " + tempFT.firstName +"(Full Time)" + "\nEmployee Number: "+ tempFT.employeeNumber + "\nGender: " + tempFT.gender +"\nDeduction Rate:" +tempFT.deductionRate+"\nYearly Salary:" +tempFT.yearlySalary+ "\nNet Income:" + tempFT.netIncome);   
                      }
                  }
        }
        
    }//GEN-LAST:event_displayButtonActionPerformed

    private void ptRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptRadioActionPerformed
        
        hourlyWageField.setEnabled (true);
        hrsPerWeekField.setEnabled (true);
        weeksPerYearField.setEnabled (true);
        yearlySalaryField.setEnabled (false);
        
    }//GEN-LAST:event_ptRadioActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void dbChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbChooserActionPerformed

        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            dbChooserFrame.setVisible(false);
            dataBase = dbChooser.getSelectedFile().getPath();
            hTable.open(dataBase);
            outputField.setText("Database loaded succesfully!");
            
        } catch (IOException ex) {
           outputField.setText("Problem accessing file");
        }
    }//GEN-LAST:event_dbChooserActionPerformed

    private void saveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileActionPerformed

         try {

            hTable.save(dataBase);
        } catch (IOException ex) {
            Logger.getLogger(EmployeeUI.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
        
    }//GEN-LAST:event_saveFileActionPerformed

    private void employeeNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNumberFieldActionPerformed

    private void middleNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameFieldActionPerformed

    private void CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateActionPerformed
if (ftRadio.isSelected()) {
         
             dRate = Double.parseDouble (deductionRateField.getText());
             yearlySalary = Double.parseDouble(yearlySalaryField.getText());  
             
             nIncome = yearlySalary * (1 - (dRate / 100));
             netIncomeField.setText(Double.toString(nIncome));
        
        } 
         else {
            if (ptRadio.isSelected()) {
            dRate = Double.parseDouble (deductionRateField.getText());    
            hourlyWage = Double.parseDouble (hourlyWageField.getText());
            hrsPerWeek = Float.parseFloat (hrsPerWeekField.getText());
            weeksPerYear = Integer.parseInt (weeksPerYearField.getText());        
            nIncome = (hourlyWage * hrsPerWeek * weeksPerYear) * (1 - (dRate / 100));
            netIncomeField.setText(Double.toString(nIncome));


            }
            else{
            netIncomeField.setText("Please Select Occupation Type");
            }   
            
         }            // TODO add your handling code here:
        
        
    }//GEN-LAST:event_CalculateActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
       tempEmployee = hTable.search(Integer.parseInt(searchField.getText()));
        
        if (tempEmployee == null){
            outputField.setText("No employee with that employee number exists.");
        }
        else {
  
            outputField.setText(" Specified Employee: "+ "\n" + tempEmployee.lastName + ", " + tempEmployee.middleName + " " + tempEmployee.firstName + "\nEmployee Number: "+ tempEmployee.employeeNumber + "\nGender: " + tempEmployee.gender + "\nNet Income:" + tempEmployee.netIncome);
     
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        tempEmployee = hTable.search(Integer.parseInt(searchField.getText()));
                // TODO add your handling code here:
        if (tempEmployee == null ){
            outputField.setText("Cannot Modify" + "/n" + " Employee with that employee number does not exist.");
            
        }
        else{
            if (tempEmployee instanceof PartTime){ 
           tempPT = (PartTime) tempEmployee;
             
         firstNameField.setText(tempPT.firstName);
         middleNameField.setText(tempPT.middleName);
         lastNameField.setText(tempPT.lastName);
         employeeNumberField.setText(Integer.toString(tempPT.employeeNumber));
         deductionRateField.setText(Double.toString(tempPT.deductionRate));
         ptRadio.setSelected(true);
         if (gender == "Male") {
             genderBox.setSelectedItem("Male");
         }
         else{
             genderBox.setSelectedItem("Female");
         }
         hourlyWageField.setText(Double.toString(tempPT.hourlyWage));
         hrsPerWeekField.setText(Float.toString(tempPT.hrsPerWeek));
         weeksPerYearField.setText(Integer.toString(tempPT.weeksPerYear));
         netIncomeField.setText(Double.toString (tempPT.netIncome));
         hTable.delete(tempPT.employeeNumber);
            }
           if (tempEmployee instanceof FullTime){
                tempFT = (FullTime) tempEmployee;
             
         firstNameField.setText(tempFT.firstName);
         middleNameField.setText(tempFT.middleName);
         lastNameField.setText(tempFT.lastName);
         employeeNumberField.setText(Integer.toString(tempFT.employeeNumber));
         deductionRateField.setText(Double.toString(tempFT.deductionRate));
         if (gender == "Male") {
         genderBox.setSelectedItem("Male");
         }
         else{
             genderBox.setSelectedItem("Female");
         }
         ftRadio.setSelected(true);
         hourlyWageField.setText(Double.toString(tempFT.yearlySalary));
         netIncomeField.setText(Double.toString (tempFT.netIncome));
         hTable.delete(tempFT.employeeNumber);
           }
        }
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
    tempEmployee = hTable.search(Integer.parseInt(searchField.getText()));        // TODO add your handling code here:
    if (tempEmployee == null){
        outputField.setText("No employee with that employee number exists.");
    }
    else{
        hTable.delete(tempEmployee.employeeNumber);
    outputField.setText("Employee Number: "+ tempEmployee.employeeNumber+ " deleted." );
    }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
      EmployeeUI gui = new EmployeeUI ();
      gui.setVisible (true);
     
    
     
      
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calculate;
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFileChooser dbChooser;
    private javax.swing.JFrame dbChooserFrame;
    private javax.swing.JTextField deductionRateField;
    private javax.swing.JLabel deductionRateLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton displayButton;
    private javax.swing.JTextField employeeNumberField;
    private javax.swing.JLabel employeeNumberLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JRadioButton ftRadio;
    private javax.swing.JComboBox genderBox;
    private javax.swing.JTextField hourlyWageField;
    private javax.swing.JLabel hrlyWageLabel;
    private javax.swing.JTextField hrsPerWeekField;
    private javax.swing.JLabel hrsPerWeekLabel;
    private javax.swing.JLabel hrsPerYearLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField middleNameField;
    private javax.swing.JLabel middleNameLabel1;
    private javax.swing.JButton modifyButton;
    private javax.swing.JTextField netIncomeField;
    private javax.swing.JLabel occupationTypeLabel;
    private javax.swing.JMenuItem openFile;
    private javax.swing.JTextArea outputField;
    private javax.swing.JRadioButton ptRadio;
    private javax.swing.JMenuItem saveFile;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JTextField weeksPerYearField;
    private javax.swing.JTextField yearlySalaryField;
    // End of variables declaration//GEN-END:variables

}